apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: smart-task-manager
    tier: frontend
spec:
  selector:
    app: smart-task-manager
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # For external access